<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <AssemblyVersion>2027.0.0</AssemblyVersion>
    <FileVersion>2027.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1210.39" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Autodesk.Connectivity.Explorer.Extensibility">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.Connectivity.Explorer.Extensibility.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.Connectivity.Explorer.ExtensibilityTools">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.Connectivity.Explorer.ExtensibilityTools.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.Connectivity.Extensibility.Framework">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.Connectivity.Extensibility.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.Connectivity.WebServices">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.Connectivity.WebServices.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework.Forms">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.Forms.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework.Vault">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.Vault.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Readme.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="VaultCloudLinkExtension.vcet.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="VaultCloudLinkSettings.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /E /I /Y &quot;$(TargetDir)*&quot; &quot;C:\ProgramData\Autodesk\Vault 2027\Extensions\CloudLinkExtension&quot;" />
  </Target>

</Project>
